apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tatara-memory-repo-ingester.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tatara-memory-repo-ingester.labels" . | nindent 4 }}
data:
  {{- include "tatara-memory-repo-ingester.envConfig" . | nindent 2 }}
